version: '3'
services:
  silverstripe:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www
    env_file:
      - .env
    volumes:
      - .:/var/www/
    tty: true
    links:
      - mariadb

  mariadb:
    image: mariadb
    restart: always
    volumes:
      - mariadb-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: silverstripe
      MYSQL_ROOT_PASSWORD: password

volumes:
  mariadb-volume:
